// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2025, 4:01:31 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquisabah/Documents/storipod-new-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/plugins/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/storipod-new-website/composables/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/storipod-new-website/utils/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/storipod-new-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/storipod-new-website/app.config.{js,ts,mjs}","/Users/marquisabah/Documents/storipod-new-website/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;